title: Blog Posts
description: My Personal Blog Posts
author: Hari Devanathan
github: https://github.com/hd2zm
about: Aspiring Data Scientist
google_analytics: UA-XXXXXXXX-Y
avatar_url: /images/portrait/Head.jpeg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/hari-devanathan-16698a36"
    - icon: fa-github
      link: "https://github.com/hd2zm"

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/

url: "http://127.0.0.1:4000"
baseurl: ""
markdown: kramdown
gems:
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
